# Generated by Django 3.2.9 on 2023-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='deep_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Забанен(а)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, help_text='Язык', max_length=8, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
    ]
