# Generated by Django 3.2.9 on 2023-05-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
    ]
