# Generated by Django 3.2.9 on 2023-05-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chats",
            options={"verbose_name_plural": "Chats"},
        ),
    ]
