START_OVER = False
ACTIVATE = False
# STATES
(
    START,
    END,
    ASK_QUESTION,
    ASKING_QUESTION,
    EXPORT_QUESTIONS,
    SUPPORT_CHAT,
    SELECT_SUPPORT_CHAT,
) = (
    "START",
    "END",
    "ASK_QUESTION",
    "ASKING_QUESTION",
    "EXPORT_QUESTIONS",
    "SUPPORT_CHAT",
    "SUPPORT_CHAT_",
)

# BUTTONS

(
    SELECTING_ACTION,
    STOPPING,
    SHOWING,
    SELECTING_LEVEL,
    QUESTION,
    TYPING,
    HELP,
    SUPPORT_CHAT_AND_NUMBER,
    STOP_BOT,
    SELECTING_SUPPORT_CHAT,
    SELECT_STOP_BOT,
    SELECT_STOP_AND_REMOVE_ALL,
    SELECTING_FEATURE,
    HAS_QUESTION,
    CURRENT_LEVEL,
) = [
    "SELECTING_ACTION",
    "STOPPING",
    "SHOWING",
    "SELECTING_LEVEL",
    "QUESTION",
    "TYPING",
    "HELP",
    "SUPPORT_CHAT_.*",
    "STOP_BOT",
    "SELECTING_SUPPORT_CHAT",
    "SELECT_STOP_BOT",
    "SELECT_STOP_AND_REMOVE_ALL",
    "SELECTING_FEATURE",
    "HAS_QUESTION",
    "CURRENT_LEVEL",
]

STATES_NO_CHAT_SUPPORT = [QUESTION, END]
