START_OVER = False
ACTIVATE = False
# STATES
(
    START,
    END,
    ASK_QUESTION,
    ASKING_QUESTION,
    EXPORT_QUESTIONS,
    SUPPORT_CHAT,
    SELECT_SUPPORT_CHAT,
) = (
    "START",
    "END",
    "ASK_QUESTION",
    "ASKING_QUESTION",
    "EXPORT_QUESTIONS",
    "SUPPORT_CHAT",
    "SUPPORT_CHAT_",
)

# BUTTONS
(
    SELECTING_ACTION,
    STOPPING,
    SHOWING,
    SELECTING_LEVEL,
    QUESTION,
    TYPING,
    HELP,
    SUPPORT_CHAT_AND_NUMBER,
    STOP_BOT,
    SELECTING_SUPPORT_CHAT,
    SELECT_STOP_BOT,
    SELECT_STOP_AND_REMOVE_ALL,
    SELECTING_FEATURE,
    HAS_QUESTION,
    CURRENT_LEVEL,
    BAN,
    BAN_LIST
) = [
    "SELECTING_ACTION",
    "STOPPING",
    "SHOWING",
    "SELECTING_LEVEL",
    "QUESTION",
    "TYPING",
    "HELP",
    "SUPPORT_CHAT_.*",
    "STOP_BOT",
    "SELECTING_SUPPORT_CHAT",
    "SELECT_STOP_BOT",
    "SELECT_STOP_AND_REMOVE_ALL",
    "SELECTING_FEATURE",
    "HAS_QUESTION",
    "CURRENT_LEVEL",
    "BAN",
    "BAN_LIST"
]

# BANHAMMER BUTTONS
PREV_, NEXT_, BAN_ALL, SAVE_BAN, ITEM_ = ["prev_.*", "next_.*", "ban_all", "save_ban", "item_.*"]

# BANHAMMER MARKUP
BANHAMMER_REPLY_MARKUP = "BANHAMMER_REPLY_MARKUP"

STATES_NO_CHAT_SUPPORT = [QUESTION, END]

START_COMMAND, STOP_COMMAND = '/start', '/stop'